local _ctx = context() 

print[[
/* Generated by state.lua, do not edit by hand */

#include <stdbool.h>]]

local defs = {}
for k, v in pairs(_ctx.defines) do
	defs[#defs+1] = k
end
table.sort(defs)
for _, k in ipairs(defs) do
	print('#define ' .. k .. ' ' .. _ctx.defines[k])
end
print()
for _, name_t_members in ipairs(_ctx.typedefs) do
	local name, t, members = table.unpack(name_t_members)
	if _ctx.isextern[name] then print('/* @extern') end
	print(t ..' ' .. name .. ' {')
	if t == 'enum' then
		local ik, min, max = {}, math.huge, -math.huge
		for k, i in pairs(members) do
			ik[i] = k
			if i < min then min = i end
			if i > max then max = i end
		end
		for i = min, max do
			if ik[i] then
				print('  ' .. ik[i] .. ' = ' .. i .. ',')
			end
		end
	elseif t == 'struct' then
		local keys = {}
		for k in pairs(members) do
			keys[#keys+1] = k
		end
		table.sort(keys)
		for _, k in ipairs(keys) do
			print('  ' .. members[k](k) .. ';')
		end
	else
		error('Unimplemented type ' .. tostring(t))
	end
	print('};')
	if _ctx.isextern[name] then print('*/') end
	print()
end
